-- patch_v12_drop_all_functions.sql
-- Drop ALL stored functions so functions.sql can be applied from scratch.
-- Used once after v12 normalization changes function return types.

-- Whitelist functions
DROP FUNCTION IF EXISTS users_get_by_email(TEXT) CASCADE;
DROP FUNCTION IF EXISTS whitelist_state_get() CASCADE;
DROP FUNCTION IF EXISTS whitelist_addresses_all() CASCADE;
DROP FUNCTION IF EXISTS whitelist_count() CASCADE;
DROP FUNCTION IF EXISTS whitelist_entries(INT, INT) CASCADE;
DROP FUNCTION IF EXISTS whitelist_list(INT, INT) CASCADE;
DROP FUNCTION IF EXISTS whitelist_existing_lowers() CASCADE;
DROP FUNCTION IF EXISTS whitelist_entry_get(TEXT) CASCADE;
DROP FUNCTION IF EXISTS whitelist_add(TEXT, UUID) CASCADE;
DROP FUNCTION IF EXISTS whitelist_update_status(TEXT, BOOLEAN) CASCADE;
DROP FUNCTION IF EXISTS whitelist_remove(TEXT) CASCADE;
DROP FUNCTION IF EXISTS whitelist_clear() CASCADE;
DROP FUNCTION IF EXISTS whitelist_state_update_root(TEXT) CASCADE;
DROP FUNCTION IF EXISTS whitelist_state_set_override(TEXT) CASCADE;
DROP FUNCTION IF EXISTS whitelist_state_clear_override() CASCADE;

-- Master
DROP FUNCTION IF EXISTS master_get_all() CASCADE;

-- Customers
DROP FUNCTION IF EXISTS customers_list(INT, INT, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS customers_get(UUID) CASCADE;
DROP FUNCTION IF EXISTS customers_create(VARCHAR, VARCHAR, VARCHAR, TEXT, VARCHAR, VARCHAR, VARCHAR, TEXT, TEXT, TEXT, TEXT, VARCHAR) CASCADE;
DROP FUNCTION IF EXISTS customers_update(UUID, VARCHAR, VARCHAR, VARCHAR, TEXT, VARCHAR, VARCHAR, VARCHAR, TEXT, TEXT, TEXT, TEXT, VARCHAR) CASCADE;
DROP FUNCTION IF EXISTS customers_deactivate(UUID) CASCADE;

-- Referrers
DROP FUNCTION IF EXISTS referrers_list(INT, INT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS referrers_create(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR) CASCADE;

-- Orders
DROP FUNCTION IF EXISTS orders_list(INT, INT, TEXT, TEXT, UUID) CASCADE;
DROP FUNCTION IF EXISTS orders_get(UUID) CASCADE;
DROP FUNCTION IF EXISTS orders_create(UUID, VARCHAR, DATE, UUID, UUID, UUID, UUID, NUMERIC, NUMERIC, TEXT) CASCADE;
DROP FUNCTION IF EXISTS orders_update(UUID, UUID, DATE, UUID, UUID, UUID, UUID, NUMERIC, NUMERIC, TEXT) CASCADE;
DROP FUNCTION IF EXISTS orders_confirm_nft_payment(UUID, UUID) CASCADE;
DROP FUNCTION IF EXISTS orders_confirm_merch_payment(UUID, UUID) CASCADE;
DROP FUNCTION IF EXISTS orders_delete(UUID) CASCADE;

-- Products
DROP FUNCTION IF EXISTS products_list(INT, INT, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS products_get(UUID) CASCADE;
DROP FUNCTION IF EXISTS products_create(VARCHAR, TEXT, NUMERIC, INT, UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS products_update(UUID, VARCHAR, TEXT, NUMERIC, INT, UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS products_deactivate(UUID) CASCADE;

-- NFT records (two overloads of nft_list and nft_update)
DROP FUNCTION IF EXISTS nft_list(TEXT, VARCHAR, VARCHAR, BOOLEAN, INT, INT) CASCADE;
DROP FUNCTION IF EXISTS nft_list(TEXT, VARCHAR, VARCHAR, BOOLEAN, UUID, INT, INT) CASCADE;
DROP FUNCTION IF EXISTS nft_get(UUID) CASCADE;
DROP FUNCTION IF EXISTS nft_create(VARCHAR, UUID, UUID, UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS nft_update(UUID, UUID, UUID, UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS nft_update(UUID, UUID, UUID, UUID, TEXT, UUID, NUMERIC, BOOLEAN) CASCADE;
DROP FUNCTION IF EXISTS nft_confirm_delivery(UUID, UUID) CASCADE;

-- Waves
DROP FUNCTION IF EXISTS wave_list() CASCADE;
DROP FUNCTION IF EXISTS wave_get(UUID) CASCADE;
DROP FUNCTION IF EXISTS wave_upsert(INT, VARCHAR, UUID, INT, INT, INT, NUMERIC, VARCHAR, TIMESTAMPTZ, TIMESTAMPTZ, VARCHAR, TEXT) CASCADE;

-- Reconciliation
DROP FUNCTION IF EXISTS reconciliation_list(INT, INT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS reconciliation_get(UUID) CASCADE;
DROP FUNCTION IF EXISTS reconciliation_confirm(UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS reconciliation_cancel(UUID, TEXT) CASCADE;

-- Reports
DROP FUNCTION IF EXISTS reports_summary() CASCADE;

-- Users / admin
DROP FUNCTION IF EXISTS users_list(INT, INT, TEXT, UUID, BOOLEAN) CASCADE;
DROP FUNCTION IF EXISTS users_get(UUID) CASCADE;
DROP FUNCTION IF EXISTS users_create(VARCHAR, VARCHAR, VARCHAR, UUID, VARCHAR, VARCHAR, BOOLEAN, UUID) CASCADE;
DROP FUNCTION IF EXISTS users_update(UUID, VARCHAR, VARCHAR, VARCHAR, UUID, VARCHAR, VARCHAR, BOOLEAN, UUID) CASCADE;
DROP FUNCTION IF EXISTS users_deactivate(UUID) CASCADE;
DROP FUNCTION IF EXISTS users_set_permission_override(UUID, BOOLEAN) CASCADE;

-- Customer wallets
DROP FUNCTION IF EXISTS customer_wallets_list(UUID) CASCADE;
DROP FUNCTION IF EXISTS customer_wallets_add(UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS customer_wallets_remove(UUID) CASCADE;

-- NFT sell lookups
DROP FUNCTION IF EXISTS nft_sale_modes_list() CASCADE;
DROP FUNCTION IF EXISTS nft_sale_mode_upsert(VARCHAR, VARCHAR, VARCHAR, BOOLEAN, TEXT) CASCADE;
DROP FUNCTION IF EXISTS nft_currencies_list() CASCADE;
DROP FUNCTION IF EXISTS nft_currency_upsert(VARCHAR, VARCHAR, VARCHAR, BOOLEAN, BOOLEAN) CASCADE;
DROP FUNCTION IF EXISTS nft_sale_statuses_list() CASCADE;
DROP FUNCTION IF EXISTS nft_wave_sale_methods_list() CASCADE;
