/**
 * sync-db.cjs  — full schema + data sync from BearthDev → Bearth
 * Run: node scripts/sync-db.cjs
 */

"use strict";
const { Client } = require("pg");

const DEV_URL  = "postgresql://postgres:idkniaxoQBYItcwPzEaXgIvnSWaSdKIy@reseau.proxy.rlwy.net:55600/BearthDev";
const PROD_URL = "postgresql://postgres:idkniaxoQBYItcwPzEaXgIvnSWaSdKIy@reseau.proxy.rlwy.net:55600/Bearth";

// ── helpers ──────────────────────────────────────────────────────────────────

function log(msg) { console.log(`[sync] ${msg}`); }
function err(msg) { console.error(`[ERROR] ${msg}`); }

async function connect(url, label) {
  const c = new Client({ connectionString: url, ssl: { rejectUnauthorized: false } });
  await c.connect();
  log(`Connected to ${label}`);
  return c;
}

// ── 1. topology sort (tables ordered by FK dependencies) ──────────────────────

async function getTableOrder(dev) {
  // All tables in public schema
  const { rows: tables } = await dev.query(`
    SELECT tablename FROM pg_tables
    WHERE schemaname = 'public'
    ORDER BY tablename
  `);
  const allTables = tables.map(r => r.tablename);

  // FK edges: child → parent
  const { rows: fks } = await dev.query(`
    SELECT DISTINCT
      child.relname  AS child_table,
      parent.relname AS parent_table
    FROM pg_constraint c
    JOIN pg_class child  ON child.oid  = c.conrelid
    JOIN pg_class parent ON parent.oid = c.confrelid
    JOIN pg_namespace n  ON n.oid = child.relnamespace
    WHERE c.contype = 'f' AND n.nspname = 'public'
      AND child.relname <> parent.relname
  `);

  // Build adjacency
  const deps = {};
  for (const t of allTables) deps[t] = new Set();
  for (const { child_table, parent_table } of fks) {
    if (deps[child_table]) deps[child_table].add(parent_table);
  }

  // Kahn's algorithm
  const result = [];
  const visited = new Set();

  function visit(t) {
    if (visited.has(t)) return;
    visited.add(t);
    for (const dep of (deps[t] || [])) visit(dep);
    result.push(t);
  }
  for (const t of allTables) visit(t);
  return result;
}

// ── 2. DDL extraction ─────────────────────────────────────────────────────────

async function getSequencesDDL(dev) {
  const { rows } = await dev.query(`
    SELECT
      s.sequence_name,
      s.data_type,
      s.start_value,
      s.minimum_value,
      s.maximum_value,
      s.increment,
      s.cycle_option,
      -- current value
      (SELECT last_value FROM pg_sequences WHERE sequencename = s.sequence_name) AS last_value
    FROM information_schema.sequences s
    WHERE s.sequence_schema = 'public'
  `);

  return rows.map(r => {
    const cycle = r.cycle_option === 'YES' ? ' CYCLE' : ' NO CYCLE';
    let sql = `CREATE SEQUENCE IF NOT EXISTS ${r.sequence_name}`
      + ` AS ${r.data_type}`
      + ` START WITH ${r.start_value}`
      + ` INCREMENT BY ${r.increment}`
      + ` MINVALUE ${r.minimum_value}`
      + ` MAXVALUE ${r.maximum_value}`
      + cycle + `;`;
    // Advance the sequence to match current value
    if (r.last_value && BigInt(r.last_value) > BigInt(r.start_value)) {
      sql += `\nSELECT setval('${r.sequence_name}', ${r.last_value}, true);`;
    }
    return sql;
  }).join('\n');
}

async function getTableDDL(dev, tableName) {
  // Columns
  const { rows: cols } = await dev.query(`
    SELECT
      a.attname                                                   AS col,
      pg_catalog.format_type(a.atttypid, a.atttypmod)            AS dtype,
      pg_catalog.pg_get_expr(d.adbin, d.adrelid)                 AS default_val,
      a.attnotnull                                                AS not_null,
      a.attidentity                                               AS identity
    FROM pg_catalog.pg_attribute a
    LEFT JOIN pg_catalog.pg_attrdef d
      ON d.adrelid = a.attrelid AND d.adnum = a.attnum
    WHERE a.attrelid = $1::regclass
      AND a.attnum > 0
      AND NOT a.attisdropped
    ORDER BY a.attnum
  `, [`public.${tableName}`]);

  const colDefs = cols.map(c => {
    let def = `  ${c.col} ${c.dtype}`;
    if (c.identity === 'a') def += ' GENERATED ALWAYS AS IDENTITY';
    else if (c.identity === 'd') def += ' GENERATED BY DEFAULT AS IDENTITY';
    else if (c.default_val) def += ` DEFAULT ${c.default_val}`;
    if (c.not_null) def += ' NOT NULL';
    return def;
  });

  // Constraints (PK, UNIQUE, CHECK, FK)
  const { rows: cons } = await dev.query(`
    SELECT
      c.conname,
      c.contype,
      pg_catalog.pg_get_constraintdef(c.oid, true) AS def
    FROM pg_catalog.pg_constraint c
    WHERE c.conrelid = $1::regclass
    ORDER BY c.contype, c.conname
  `, [`public.${tableName}`]);

  const conDefs = cons.map(c => `  CONSTRAINT ${c.conname} ${c.def}`);

  const allDefs = [...colDefs, ...conDefs].join(',\n');
  return `CREATE TABLE IF NOT EXISTS ${tableName} (\n${allDefs}\n);`;
}

async function getIndexesDDL(dev) {
  const { rows } = await dev.query(`
    SELECT pg_get_indexdef(i.indexrelid) AS def
    FROM pg_index i
    JOIN pg_class ic ON ic.oid = i.indexrelid
    JOIN pg_class tc ON tc.oid = i.indrelid
    JOIN pg_namespace n ON n.oid = ic.relnamespace
    WHERE n.nspname = 'public'
      AND NOT i.indisprimary
      AND tc.relkind = 'r'
    ORDER BY ic.relname
  `);
  return rows.map(r => r.def + ';').join('\n');
}

async function getFunctionsDDL(dev) {
  const { rows } = await dev.query(`
    SELECT pg_get_functiondef(p.oid) AS def
    FROM pg_proc p
    JOIN pg_namespace n ON p.pronamespace = n.oid
    WHERE n.nspname = 'public'
      AND p.prokind IN ('f', 'p')
    ORDER BY p.proname
  `);
  return rows.map(r => r.def + ';').join('\n\n');
}

// ── 3. data copy ──────────────────────────────────────────────────────────────

async function copyTable(dev, prod, tableName) {
  const { rows } = await dev.query(`SELECT * FROM ${tableName}`);
  if (rows.length === 0) return 0;

  const cols = Object.keys(rows[0]);
  const colList = cols.map(c => `"${c}"`).join(', ');

  // Batch inserts of 500 rows
  const BATCH = 500;
  let inserted = 0;
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    const values = [];
    const params = [];
    let pIdx = 1;
    for (const row of batch) {
      const rowParams = cols.map(() => `$${pIdx++}`);
      values.push(`(${rowParams.join(', ')})`);
      params.push(...cols.map(c => row[c]));
    }
    await prod.query(
      `INSERT INTO ${tableName} (${colList}) VALUES ${values.join(', ')} ON CONFLICT DO NOTHING`,
      params
    );
    inserted += batch.length;
  }
  return inserted;
}

// ── main ──────────────────────────────────────────────────────────────────────

async function main() {
  const dev  = await connect(DEV_URL,  'BearthDev');
  const prod = await connect(PROD_URL, 'Bearth');

  try {
    // ── Step 1: Schema ─────────────────────────────────────────────────
    log('Extracting schema from BearthDev...');

    const tableOrder = await getTableOrder(dev);
    log(`Tables to create (${tableOrder.length}): ${tableOrder.join(', ')}`);

    // Sequences
    const seqSQL = await getSequencesDDL(dev);

    // Tables DDL
    const tableSQLs = [];
    for (const t of tableOrder) {
      tableSQLs.push(await getTableDDL(dev, t));
    }

    // Indexes
    const idxSQL = await getIndexesDDL(dev);

    // Functions
    const fnSQL = await getFunctionsDDL(dev);

    // ── Step 2: Apply schema to Bearth ─────────────────────────────────
    log('Applying schema to Bearth...');

    // Disable FK checks for schema creation
    await prod.query('SET session_replication_role = replica');

    if (seqSQL.trim()) {
      log('  Creating sequences...');
      await prod.query(seqSQL);
    }

    log('  Creating tables...');
    for (let i = 0; i < tableOrder.length; i++) {
      const t = tableOrder[i];
      try {
        await prod.query(tableSQLs[i]);
        log(`    ✓ ${t}`);
      } catch (e) {
        err(`    ✗ ${t}: ${e.message}`);
        throw e;
      }
    }

    if (idxSQL.trim()) {
      log('  Creating indexes...');
      // Apply indexes one by one so a single failure is isolated
      for (const line of idxSQL.split('\n').filter(l => l.trim())) {
        try { await prod.query(line); } catch (e) {
          if (!e.message.includes('already exists')) err(`  Index warning: ${e.message}`);
        }
      }
    }

    if (fnSQL.trim()) {
      log('  Creating functions...');
      try {
        await prod.query(fnSQL);
      } catch (e) {
        err(`  Functions warning: ${e.message}`);
      }
    }

    // ── Step 3: Copy data ───────────────────────────────────────────────
    log('Copying data...');
    let totalRows = 0;
    for (const t of tableOrder) {
      try {
        const n = await copyTable(dev, prod, t);
        if (n > 0) log(`  ✓ ${t}: ${n} rows`);
        else log(`  - ${t}: empty`);
        totalRows += n;
      } catch (e) {
        err(`  ✗ ${t}: ${e.message}`);
        throw e;
      }
    }

    // Re-enable FK checks
    await prod.query('SET session_replication_role = DEFAULT');

    log(`\n✅ Sync complete — ${tableOrder.length} tables, ${totalRows} total rows copied to Bearth`);

  } finally {
    await dev.end();
    await prod.end();
  }
}

main().catch(e => { err(e.message); process.exit(1); });
